# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - analyzing-pandemic-response

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://analyzingpandemicresponse.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca0747b58da94e6988023f2c9e38b994 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f823589ecd644f7b4161f51ee277d98 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: analyzingpandemicresponse.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca0747b58da94e6988023f2c9e38b994 }}/arp-dash:${{ github.sha }}
        file: ./app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'analyzing-pandemic-response'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_723cd66ca1914e58b55c24b9afdb43d9 }}
        images: 'analyzingpandemicresponse.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca0747b58da94e6988023f2c9e38b994 }}/arp-dash:${{ github.sha }}'
